print("hola mundo te digo 'hola'")
print(100)
print(100+1)
print("hola mundo te digo 'hola'"+" Seba")
print("5 hola mundo me llamo \"seba\"")
print("6 Esta es una linea \n y esta es otra linea")
print("\t 7 esta es una linea tabulada")
print("8 palabra \' con apostrofe")
print("9 este signo es una barra invertida \\ ")
print('Línea 1\nLínea 2\nLínea 3')
print(input("dime tu nombre: "))
print("tu nombre es: "+input("dime tu nombre ")+" "+input("dime tu apellido: "))
print("tu cerveza se llamara: \n"+input("dime un color ")+" "+input("dime tu  signo: "))